apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api_ans_poetisa
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

