apiVersion: v1
kind: Service
metadata:
  name: api-metrics
  labels:
    app: api-metrics
spec:
  selector:
    app: api-metrics
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30500
  type: "NodePort"
  