apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    nodePort: 30500
  type: "NodePort"
  