apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api-metrics
  name: api-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-metrics
    spec:
      containers:
        - name: api-metrics
          image: api_metrics_poetisa
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
